#pragma once

#define HOSTNAME "ESP32"
#define MAC_WIFI "00000"
#define MAC_BLUETOOTH "00000"
#define CURRENT_VERSION "0"
#define HARDWARE_DESCRIPTION "1234567"

#define CONTROL_MODE_SHELL 0
#define CONTROL_MODE_BINARY 1
#define SELECTED_CONTROL_MODE CONTROL_MODE_SHELL

#define NON_SHELL_MODE_ERROR_CODE "KO"

#define MAX_OUTPUT_SIZE 10000